environment:
  CURRENT_VERSION: 0.9.0
version: 0.9.0-{build}
branches:
  only:
    - master
    - develop
    - release/*
    - feature/*
os: Windows Server 2012
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(CURRENT_VERSION).{build}"
  assembly_file_version: "$(CURRENT_VERSION).{build}"
  assembly_informational_version: "$(CURRENT_VERSION).{build}"
cache:
  - packages
configuration:
  - Debug
  - Release
after_build:
  - nuget pack Nerdery.Umbraco.Vault/Nerdery.Umbraco.Vault.csproj -Symbols -Version %CURRENT_VERSION%-build%APPVEYOR_BUILD_NUMBER%
  - nuget pack Nerdery.Umbraco.Vault/Nerdery.Umbraco.Vault.csproj -Version %CURRENT_VERSION%
  - nuget pack Nerdery.Umbraco.Vault/Nerdery.Umbraco.VaultExtensions.csproj -Symbols -Version %CURRENT_VERSION%-build%APPVEYOR_BUILD_NUMBER%
  - nuget pack Nerdery.Umbraco.Vault/Nerdery.Umbraco.VaultExtensions.csproj -Version %CURRENT_VERSION%
artifacts:
  - path: "*.nupkg"
deploy:
  - provider: NuGet
    server: https://nuget.nerderylabs.com/
    api_key:
      secure: 0ToyIMPccSDucw5aqB9Yf0jNLcxaCWIhgTMpc00hndc=
    artifact: /Nerdery\.Umbraco\.Vault\.([0-9]+)\.([0-9]+)\.([0-9]+)-build(.*)\.nupkg/
    on:
      branch: develop
      configuration: Debug
  - provider: NuGet
    server: https://nuget.nerderylabs.com/
    api_key:
      secure: 0ToyIMPccSDucw5aqB9Yf0jNLcxaCWIhgTMpc00hndc=
    artifact: /Nerdery\.Umbraco\.VaultExtensions\.([0-9]+)\.([0-9]+)\.([0-9]+)-build(.*)\.nupkg/
    on:
      branch: develop
      configuration: Debug