environment:
  CURRENT_VERSION: 1.0.3
version: 1.0.3-{build}
branches:
  only:
    - master
    - develop
    - release/*
    - feature/*
os: Visual Studio 2015
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(CURRENT_VERSION).0"
  assembly_file_version: "$(CURRENT_VERSION).0"
  assembly_informational_version: "$(CURRENT_VERSION).0"
configuration:
  - Release
before_build:
  - nuget restore
after_build:
  - nuget pack UmbracoVault.uComponents/UmbracoVault.uComponents.csproj -Symbols -Version %CURRENT_VERSION%-build%APPVEYOR_BUILD_NUMBER%
  - nuget pack UmbracoVault.uComponents/UmbracoVault.uComponents.csproj -Symbols -Version %CURRENT_VERSION%-alpha1
artifacts:
  - path: '*.nupkg'
