environment:
  CURRENT_VERSION: 1.0.0
version: 1.0.0-{build}
branches:
  only:
    - master
    - develop
    - release/*
    - feature/*
os: Windows Server 2012
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(CURRENT_VERSION).0"
  assembly_file_version: "$(CURRENT_VERSION).0"
  assembly_informational_version: "$(CURRENT_VERSION).0"
cache:
  - packages
configuration:
  - Debug
  - Release
after_build:
  - nuget pack UmbracoVault.uComponents/UmbracoVault.uComponents.csproj -Symbols -Version %CURRENT_VERSION%-build%APPVEYOR_BUILD_NUMBER%
  - nuget pack UmbracoVault.uComponents/UmbracoVault.uComponents.csproj -Symbols -Version %CURRENT_VERSION%
artifacts:
  - path: '*.nupkg'
