environment:
  CURRENT_VERSION: 0.9.0
  NUGET_PASSWORD:
    secure: he7pAFfqI8jwtrzC5NzrlGg/gFOEEQ3Mk8cPuHfH9xg=
version: 0.9.0-{build}
branches:
  only:
    - master
    - develop
    - release/*
    - feature/*
os: Windows Server 2012
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(CURRENT_VERSION).{build}"
  assembly_file_version: "$(CURRENT_VERSION).{build}"
  assembly_informational_version: "$(CURRENT_VERSION).{build}"
cache:
  - packages
configuration:
  - Debug
  - Release
before_build:
  - nuget Sources Add -Name UmbracoVaultBuild -Source https://ci.appveyor.com/nuget/umbracovault-5m6ate96gcwx -UserName ksykora@nerdery.com -Password "%NUGET_PASSWORD%"
after_build:
  - nuget pack UmbracoVault.uComponents/UmbracoVault.uComponents.csproj -Symbols -Version %CURRENT_VERSION%-build%APPVEYOR_BUILD_NUMBER%
  - nuget pack UmbracoVault.uComponents/UmbracoVault.uComponents.csproj -Version %CURRENT_VERSION%
artifacts:
  - path: '*.nupkg'
